/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Pipeline Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Response body for pipeline save.
type PipelineSaveResponseBody struct {
	Identifier         string               `json:"identifier,omitempty"`
	GovernanceMetadata []GovernanceMetadata `json:"governance_metadata,omitempty"`
}
