/*
 * Infrastructure as Code Management
 *
 * Services for Harness IaCM Module.
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// AnsibleHost is a collection of variables keyed by variable name for a single ansible host.
type AnsibleHost map[string]AnsibleVariable
