/*
 * Infrastructure as Code Management
 *
 * Services for Harness IaCM Module.
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type PostFilesResponseBody struct {
	// Indicates if the provider version is synced
	Synced bool `json:"synced,omitempty"`
}
