/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Pipeline Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Parameters related to importing an entity for Git.
type GitImportInfo struct {
	ConnectorRef  string `json:"connector_ref,omitempty"`
	RepoName      string `json:"repo_name,omitempty"`
	BranchName    string `json:"branch_name,omitempty"`
	FilePath      string `json:"file_path,omitempty"`
	IsForceImport bool   `json:"is_force_import,omitempty"`
}
