/*
 * Infrastructure as Code Management
 *
 * Services for Harness IaCM Module.
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type ShowInventoryResponse struct {
	// Account is the internal customer account ID.
	Account string `json:"account"`
	// Timestamp when the resource was created.
	Created int64 `json:"created"`
	// The data representing the inventory
	Data string `json:"data"`
	// The unique identifier for this inventory
	Identifier string `json:"identifier"`
	// Name is the human readable name
	Name string `json:"name"`
	// Org is the organisation identifier.
	Org string `json:"org"`
	// Project is the project identifier.
	Project string `json:"project"`
	// Tags associated with the inventory
	Tags string `json:"tags,omitempty"`
	// Type indicates what kind of inventory this is
	Type_ string `json:"type"`
	// Timestamp when the resource was last updated.
	Updated int64 `json:"updated"`
}
