/*
 * api/v1/gitops_service.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type ClustersClusterInfo struct {
	ConnectionState   *CommonsConnectionState   `json:"connectionState,omitempty"`
	ServerVersion     string                    `json:"serverVersion,omitempty"`
	CacheInfo         *ClustersClusterCacheInfo `json:"cacheInfo,omitempty"`
	ApplicationsCount string                    `json:"applicationsCount,omitempty"`
	ApiVersions       []string                  `json:"apiVersions,omitempty"`
}
