/*
 * Lightwing APIs
 *
 * Lightwing API documentation
 *
 * API version: 1.0.0
 * Contact: navaneeth@lightwing.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Defines which entities (AutoStopping rules) the alert applies to. Use 'all' to apply to all rules, or 'specific' with entity_id to target specific rules.
type AlertEntity struct {
    AlertEntityAll
    AlertEntitySpecific
}
