/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Pipeline Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Entity details
type NodeInfo struct {
	// Entity identifier
	Identifier string `json:"identifier,omitempty"`
	// Type of Entity
	Type_ string `json:"type,omitempty"`
	// Name of Entity
	Name string `json:"name,omitempty"`
	// Fully Qualified Name
	Fqn string `json:"fqn,omitempty"`
}
