/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Pipeline Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Information about parent pipeline
type ParentStageInfo struct {
	// boolean to describe whether or not this was executed through pipeline chaining
	HasParentPipeline bool `json:"has_parent_pipeline,omitempty"`
	// planExecutionId of parent pipeline execution
	ExecutionId string `json:"execution_id,omitempty"`
	// pipeline identifier of parent pipeline
	Identifier string `json:"identifier,omitempty"`
	// project identifier
	ProjectId string `json:"project_id,omitempty"`
	// org identifier
	OrgId string `json:"org_id,omitempty"`
	// run sequence of parent pipeline execution
	RunSequence int32 `json:"run_sequence,omitempty"`
	// node id of parent pipeline stage
	StageNodeId string `json:"stage_node_id,omitempty"`
}
