/*
 * Harness NextGen Software Delivery Platform API Reference
 *
 * This is the Open Api Spec 3 for the Pipeline Service. This is under active development. Beware of the breaking change with respect to the generated code stub.
 *
 * API version: 1.0
 * Contact: contact@harness.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// Parameters related to moving an entity for Git Experience.
type GitMoveDetails struct {
	// Name of the branch. When moving an inline pipeline or a remote pipeline, this branch is where the remote entity is created or fetched.
	BranchName string `json:"branch_name,omitempty"`
	// File path of the entity in the repository.
	FilePath string `json:"file_path,omitempty"`
	// Merge commit message.
	CommitMessage string `json:"commit_message,omitempty"`
	// Default branch name. This checks out the branch titled branch_name
	BaseBranch string `json:"base_branch,omitempty"`
	// Harness connector id used for entity CRUD operations
	ConnectorRef string `json:"connector_ref,omitempty"`
	// Name of the repository.
	RepoName string `json:"repo_name,omitempty"`
}
