/*
 * Lightwing APIs
 *
 * Lightwing API documentation
 *
 * API version: 1.0.0
 * Contact: navaneeth@lightwing.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

type AlertRequest struct {
	// Unique identifier of the alert. Required for update operations.
	Id string `json:"id,omitempty"`
	// Name of the alert
	Name string `json:"name"`
	// Whether the alert is enabled
	Enabled bool `json:"enabled,omitempty"`
	// Type of entity the alert is associated with
	EntityType string `json:"entity_type"`
	// List of notification recipients. At least one recipient is required.
	Recipients []AlertRecipient `json:"recipients"`
	// List of events that trigger the alert. At least one event is required.
	Events []AlertEvent `json:"events"`
	// List of entities associated with this alert. Use relation_type 'all' to apply to all AutoStopping rules, or 'specific' with entity_id to target specific rules.
	AssociatedEntities []AlertEntity `json:"associated_entities"`
}
