/*
 * Infrastructure as Code Management
 *
 * Services for Harness IaCM Module.
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nextgen

// SigningKey contains a GPG key for provider verification (default view)
type SigningKey struct {
	// ASCII-armored GPG public key
	AsciiArmor string `json:"ascii_armor"`
	// Creation timestamp
	CreatedAt string `json:"created_at"`
	// ID of the signing key
	Id string `json:"id"`
	// GPG key ID
	KeyId string `json:"key_id"`
	// GPG key name
	KeyName string `json:"name"`
	// Last updated timestamp
	UpdatedAt string `json:"updated_at"`
	// User who uploaded the key
	User string `json:"user"`
}
