/*
Harness Artifact Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package har

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RegistryArtifactMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RegistryArtifactMetadata{}

// RegistryArtifactMetadata Artifact Metadata
type RegistryArtifactMetadata struct {
	DownloadsCount *int64 `json:"downloadsCount,omitempty"`
	Labels []string `json:"labels,omitempty"`
	LastModified *string `json:"lastModified,omitempty"`
	LatestVersion string `json:"latestVersion"`
	Name string `json:"name"`
	PackageType *PackageType `json:"packageType,omitempty"`
	RegistryIdentifier string `json:"registryIdentifier"`
	RegistryPath string `json:"registryPath"`
}

type _RegistryArtifactMetadata RegistryArtifactMetadata

// NewRegistryArtifactMetadata instantiates a new RegistryArtifactMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRegistryArtifactMetadata(latestVersion string, name string, registryIdentifier string, registryPath string) *RegistryArtifactMetadata {
	this := RegistryArtifactMetadata{}
	this.LatestVersion = latestVersion
	this.Name = name
	this.RegistryIdentifier = registryIdentifier
	this.RegistryPath = registryPath
	return &this
}

// NewRegistryArtifactMetadataWithDefaults instantiates a new RegistryArtifactMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRegistryArtifactMetadataWithDefaults() *RegistryArtifactMetadata {
	this := RegistryArtifactMetadata{}
	return &this
}

// GetDownloadsCount returns the DownloadsCount field value if set, zero value otherwise.
func (o *RegistryArtifactMetadata) GetDownloadsCount() int64 {
	if o == nil || IsNil(o.DownloadsCount) {
		var ret int64
		return ret
	}
	return *o.DownloadsCount
}

// GetDownloadsCountOk returns a tuple with the DownloadsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryArtifactMetadata) GetDownloadsCountOk() (*int64, bool) {
	if o == nil || IsNil(o.DownloadsCount) {
		return nil, false
	}
	return o.DownloadsCount, true
}

// HasDownloadsCount returns a boolean if a field has been set.
func (o *RegistryArtifactMetadata) HasDownloadsCount() bool {
	if o != nil && !IsNil(o.DownloadsCount) {
		return true
	}

	return false
}

// SetDownloadsCount gets a reference to the given int64 and assigns it to the DownloadsCount field.
func (o *RegistryArtifactMetadata) SetDownloadsCount(v int64) {
	o.DownloadsCount = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *RegistryArtifactMetadata) GetLabels() []string {
	if o == nil || IsNil(o.Labels) {
		var ret []string
		return ret
	}
	return o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryArtifactMetadata) GetLabelsOk() ([]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *RegistryArtifactMetadata) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given []string and assigns it to the Labels field.
func (o *RegistryArtifactMetadata) SetLabels(v []string) {
	o.Labels = v
}

// GetLastModified returns the LastModified field value if set, zero value otherwise.
func (o *RegistryArtifactMetadata) GetLastModified() string {
	if o == nil || IsNil(o.LastModified) {
		var ret string
		return ret
	}
	return *o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryArtifactMetadata) GetLastModifiedOk() (*string, bool) {
	if o == nil || IsNil(o.LastModified) {
		return nil, false
	}
	return o.LastModified, true
}

// HasLastModified returns a boolean if a field has been set.
func (o *RegistryArtifactMetadata) HasLastModified() bool {
	if o != nil && !IsNil(o.LastModified) {
		return true
	}

	return false
}

// SetLastModified gets a reference to the given string and assigns it to the LastModified field.
func (o *RegistryArtifactMetadata) SetLastModified(v string) {
	o.LastModified = &v
}

// GetLatestVersion returns the LatestVersion field value
func (o *RegistryArtifactMetadata) GetLatestVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LatestVersion
}

// GetLatestVersionOk returns a tuple with the LatestVersion field value
// and a boolean to check if the value has been set.
func (o *RegistryArtifactMetadata) GetLatestVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LatestVersion, true
}

// SetLatestVersion sets field value
func (o *RegistryArtifactMetadata) SetLatestVersion(v string) {
	o.LatestVersion = v
}

// GetName returns the Name field value
func (o *RegistryArtifactMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RegistryArtifactMetadata) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RegistryArtifactMetadata) SetName(v string) {
	o.Name = v
}

// GetPackageType returns the PackageType field value if set, zero value otherwise.
func (o *RegistryArtifactMetadata) GetPackageType() PackageType {
	if o == nil || IsNil(o.PackageType) {
		var ret PackageType
		return ret
	}
	return *o.PackageType
}

// GetPackageTypeOk returns a tuple with the PackageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RegistryArtifactMetadata) GetPackageTypeOk() (*PackageType, bool) {
	if o == nil || IsNil(o.PackageType) {
		return nil, false
	}
	return o.PackageType, true
}

// HasPackageType returns a boolean if a field has been set.
func (o *RegistryArtifactMetadata) HasPackageType() bool {
	if o != nil && !IsNil(o.PackageType) {
		return true
	}

	return false
}

// SetPackageType gets a reference to the given PackageType and assigns it to the PackageType field.
func (o *RegistryArtifactMetadata) SetPackageType(v PackageType) {
	o.PackageType = &v
}

// GetRegistryIdentifier returns the RegistryIdentifier field value
func (o *RegistryArtifactMetadata) GetRegistryIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistryIdentifier
}

// GetRegistryIdentifierOk returns a tuple with the RegistryIdentifier field value
// and a boolean to check if the value has been set.
func (o *RegistryArtifactMetadata) GetRegistryIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistryIdentifier, true
}

// SetRegistryIdentifier sets field value
func (o *RegistryArtifactMetadata) SetRegistryIdentifier(v string) {
	o.RegistryIdentifier = v
}

// GetRegistryPath returns the RegistryPath field value
func (o *RegistryArtifactMetadata) GetRegistryPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistryPath
}

// GetRegistryPathOk returns a tuple with the RegistryPath field value
// and a boolean to check if the value has been set.
func (o *RegistryArtifactMetadata) GetRegistryPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistryPath, true
}

// SetRegistryPath sets field value
func (o *RegistryArtifactMetadata) SetRegistryPath(v string) {
	o.RegistryPath = v
}

func (o RegistryArtifactMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RegistryArtifactMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DownloadsCount) {
		toSerialize["downloadsCount"] = o.DownloadsCount
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.LastModified) {
		toSerialize["lastModified"] = o.LastModified
	}
	toSerialize["latestVersion"] = o.LatestVersion
	toSerialize["name"] = o.Name
	if !IsNil(o.PackageType) {
		toSerialize["packageType"] = o.PackageType
	}
	toSerialize["registryIdentifier"] = o.RegistryIdentifier
	toSerialize["registryPath"] = o.RegistryPath
	return toSerialize, nil
}

func (o *RegistryArtifactMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"latestVersion",
		"name",
		"registryIdentifier",
		"registryPath",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRegistryArtifactMetadata := _RegistryArtifactMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRegistryArtifactMetadata)

	if err != nil {
		return err
	}

	*o = RegistryArtifactMetadata(varRegistryArtifactMetadata)

	return err
}

type NullableRegistryArtifactMetadata struct {
	value *RegistryArtifactMetadata
	isSet bool
}

func (v NullableRegistryArtifactMetadata) Get() *RegistryArtifactMetadata {
	return v.value
}

func (v *NullableRegistryArtifactMetadata) Set(val *RegistryArtifactMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableRegistryArtifactMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableRegistryArtifactMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRegistryArtifactMetadata(val *RegistryArtifactMetadata) *NullableRegistryArtifactMetadata {
	return &NullableRegistryArtifactMetadata{value: val, isSet: true}
}

func (v NullableRegistryArtifactMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRegistryArtifactMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


