/*
 * Harness Artifact Registry API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package har

// Config for debian artifact details
type DebianArtifactDetailConfig struct {
	Metadata map[string]interface{} `json:"metadata,omitempty"`
}
