/*
Harness Artifact Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package har

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ArtifactVersionMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ArtifactVersionMetadata{}

// ArtifactVersionMetadata Artifact Version Metadata
type ArtifactVersionMetadata struct {
	DeploymentMetadata *DeploymentMetadata `json:"deploymentMetadata,omitempty"`
	DigestCount *int64 `json:"digestCount,omitempty"`
	DownloadsCount *int64 `json:"downloadsCount,omitempty"`
	FileCount *int64 `json:"fileCount,omitempty"`
	LastModified *string `json:"lastModified,omitempty"`
	Name string `json:"name"`
	PackageType *PackageType `json:"packageType,omitempty"`
	PullCommand *string `json:"pullCommand,omitempty"`
	RegistryIdentifier string `json:"registryIdentifier"`
	RegistryPath string `json:"registryPath"`
	Size *string `json:"size,omitempty"`
}

type _ArtifactVersionMetadata ArtifactVersionMetadata

// NewArtifactVersionMetadata instantiates a new ArtifactVersionMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewArtifactVersionMetadata(name string, registryIdentifier string, registryPath string) *ArtifactVersionMetadata {
	this := ArtifactVersionMetadata{}
	this.Name = name
	this.RegistryIdentifier = registryIdentifier
	this.RegistryPath = registryPath
	return &this
}

// NewArtifactVersionMetadataWithDefaults instantiates a new ArtifactVersionMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewArtifactVersionMetadataWithDefaults() *ArtifactVersionMetadata {
	this := ArtifactVersionMetadata{}
	return &this
}

// GetDeploymentMetadata returns the DeploymentMetadata field value if set, zero value otherwise.
func (o *ArtifactVersionMetadata) GetDeploymentMetadata() DeploymentMetadata {
	if o == nil || IsNil(o.DeploymentMetadata) {
		var ret DeploymentMetadata
		return ret
	}
	return *o.DeploymentMetadata
}

// GetDeploymentMetadataOk returns a tuple with the DeploymentMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetDeploymentMetadataOk() (*DeploymentMetadata, bool) {
	if o == nil || IsNil(o.DeploymentMetadata) {
		return nil, false
	}
	return o.DeploymentMetadata, true
}

// HasDeploymentMetadata returns a boolean if a field has been set.
func (o *ArtifactVersionMetadata) HasDeploymentMetadata() bool {
	if o != nil && !IsNil(o.DeploymentMetadata) {
		return true
	}

	return false
}

// SetDeploymentMetadata gets a reference to the given DeploymentMetadata and assigns it to the DeploymentMetadata field.
func (o *ArtifactVersionMetadata) SetDeploymentMetadata(v DeploymentMetadata) {
	o.DeploymentMetadata = &v
}

// GetDigestCount returns the DigestCount field value if set, zero value otherwise.
func (o *ArtifactVersionMetadata) GetDigestCount() int64 {
	if o == nil || IsNil(o.DigestCount) {
		var ret int64
		return ret
	}
	return *o.DigestCount
}

// GetDigestCountOk returns a tuple with the DigestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetDigestCountOk() (*int64, bool) {
	if o == nil || IsNil(o.DigestCount) {
		return nil, false
	}
	return o.DigestCount, true
}

// HasDigestCount returns a boolean if a field has been set.
func (o *ArtifactVersionMetadata) HasDigestCount() bool {
	if o != nil && !IsNil(o.DigestCount) {
		return true
	}

	return false
}

// SetDigestCount gets a reference to the given int64 and assigns it to the DigestCount field.
func (o *ArtifactVersionMetadata) SetDigestCount(v int64) {
	o.DigestCount = &v
}

// GetDownloadsCount returns the DownloadsCount field value if set, zero value otherwise.
func (o *ArtifactVersionMetadata) GetDownloadsCount() int64 {
	if o == nil || IsNil(o.DownloadsCount) {
		var ret int64
		return ret
	}
	return *o.DownloadsCount
}

// GetDownloadsCountOk returns a tuple with the DownloadsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetDownloadsCountOk() (*int64, bool) {
	if o == nil || IsNil(o.DownloadsCount) {
		return nil, false
	}
	return o.DownloadsCount, true
}

// HasDownloadsCount returns a boolean if a field has been set.
func (o *ArtifactVersionMetadata) HasDownloadsCount() bool {
	if o != nil && !IsNil(o.DownloadsCount) {
		return true
	}

	return false
}

// SetDownloadsCount gets a reference to the given int64 and assigns it to the DownloadsCount field.
func (o *ArtifactVersionMetadata) SetDownloadsCount(v int64) {
	o.DownloadsCount = &v
}

// GetFileCount returns the FileCount field value if set, zero value otherwise.
func (o *ArtifactVersionMetadata) GetFileCount() int64 {
	if o == nil || IsNil(o.FileCount) {
		var ret int64
		return ret
	}
	return *o.FileCount
}

// GetFileCountOk returns a tuple with the FileCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetFileCountOk() (*int64, bool) {
	if o == nil || IsNil(o.FileCount) {
		return nil, false
	}
	return o.FileCount, true
}

// HasFileCount returns a boolean if a field has been set.
func (o *ArtifactVersionMetadata) HasFileCount() bool {
	if o != nil && !IsNil(o.FileCount) {
		return true
	}

	return false
}

// SetFileCount gets a reference to the given int64 and assigns it to the FileCount field.
func (o *ArtifactVersionMetadata) SetFileCount(v int64) {
	o.FileCount = &v
}

// GetLastModified returns the LastModified field value if set, zero value otherwise.
func (o *ArtifactVersionMetadata) GetLastModified() string {
	if o == nil || IsNil(o.LastModified) {
		var ret string
		return ret
	}
	return *o.LastModified
}

// GetLastModifiedOk returns a tuple with the LastModified field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetLastModifiedOk() (*string, bool) {
	if o == nil || IsNil(o.LastModified) {
		return nil, false
	}
	return o.LastModified, true
}

// HasLastModified returns a boolean if a field has been set.
func (o *ArtifactVersionMetadata) HasLastModified() bool {
	if o != nil && !IsNil(o.LastModified) {
		return true
	}

	return false
}

// SetLastModified gets a reference to the given string and assigns it to the LastModified field.
func (o *ArtifactVersionMetadata) SetLastModified(v string) {
	o.LastModified = &v
}

// GetName returns the Name field value
func (o *ArtifactVersionMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ArtifactVersionMetadata) SetName(v string) {
	o.Name = v
}

// GetPackageType returns the PackageType field value if set, zero value otherwise.
func (o *ArtifactVersionMetadata) GetPackageType() PackageType {
	if o == nil || IsNil(o.PackageType) {
		var ret PackageType
		return ret
	}
	return *o.PackageType
}

// GetPackageTypeOk returns a tuple with the PackageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetPackageTypeOk() (*PackageType, bool) {
	if o == nil || IsNil(o.PackageType) {
		return nil, false
	}
	return o.PackageType, true
}

// HasPackageType returns a boolean if a field has been set.
func (o *ArtifactVersionMetadata) HasPackageType() bool {
	if o != nil && !IsNil(o.PackageType) {
		return true
	}

	return false
}

// SetPackageType gets a reference to the given PackageType and assigns it to the PackageType field.
func (o *ArtifactVersionMetadata) SetPackageType(v PackageType) {
	o.PackageType = &v
}

// GetPullCommand returns the PullCommand field value if set, zero value otherwise.
func (o *ArtifactVersionMetadata) GetPullCommand() string {
	if o == nil || IsNil(o.PullCommand) {
		var ret string
		return ret
	}
	return *o.PullCommand
}

// GetPullCommandOk returns a tuple with the PullCommand field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetPullCommandOk() (*string, bool) {
	if o == nil || IsNil(o.PullCommand) {
		return nil, false
	}
	return o.PullCommand, true
}

// HasPullCommand returns a boolean if a field has been set.
func (o *ArtifactVersionMetadata) HasPullCommand() bool {
	if o != nil && !IsNil(o.PullCommand) {
		return true
	}

	return false
}

// SetPullCommand gets a reference to the given string and assigns it to the PullCommand field.
func (o *ArtifactVersionMetadata) SetPullCommand(v string) {
	o.PullCommand = &v
}

// GetRegistryIdentifier returns the RegistryIdentifier field value
func (o *ArtifactVersionMetadata) GetRegistryIdentifier() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistryIdentifier
}

// GetRegistryIdentifierOk returns a tuple with the RegistryIdentifier field value
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetRegistryIdentifierOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistryIdentifier, true
}

// SetRegistryIdentifier sets field value
func (o *ArtifactVersionMetadata) SetRegistryIdentifier(v string) {
	o.RegistryIdentifier = v
}

// GetRegistryPath returns the RegistryPath field value
func (o *ArtifactVersionMetadata) GetRegistryPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistryPath
}

// GetRegistryPathOk returns a tuple with the RegistryPath field value
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetRegistryPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistryPath, true
}

// SetRegistryPath sets field value
func (o *ArtifactVersionMetadata) SetRegistryPath(v string) {
	o.RegistryPath = v
}

// GetSize returns the Size field value if set, zero value otherwise.
func (o *ArtifactVersionMetadata) GetSize() string {
	if o == nil || IsNil(o.Size) {
		var ret string
		return ret
	}
	return *o.Size
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ArtifactVersionMetadata) GetSizeOk() (*string, bool) {
	if o == nil || IsNil(o.Size) {
		return nil, false
	}
	return o.Size, true
}

// HasSize returns a boolean if a field has been set.
func (o *ArtifactVersionMetadata) HasSize() bool {
	if o != nil && !IsNil(o.Size) {
		return true
	}

	return false
}

// SetSize gets a reference to the given string and assigns it to the Size field.
func (o *ArtifactVersionMetadata) SetSize(v string) {
	o.Size = &v
}

func (o ArtifactVersionMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ArtifactVersionMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DeploymentMetadata) {
		toSerialize["deploymentMetadata"] = o.DeploymentMetadata
	}
	if !IsNil(o.DigestCount) {
		toSerialize["digestCount"] = o.DigestCount
	}
	if !IsNil(o.DownloadsCount) {
		toSerialize["downloadsCount"] = o.DownloadsCount
	}
	if !IsNil(o.FileCount) {
		toSerialize["fileCount"] = o.FileCount
	}
	if !IsNil(o.LastModified) {
		toSerialize["lastModified"] = o.LastModified
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.PackageType) {
		toSerialize["packageType"] = o.PackageType
	}
	if !IsNil(o.PullCommand) {
		toSerialize["pullCommand"] = o.PullCommand
	}
	toSerialize["registryIdentifier"] = o.RegistryIdentifier
	toSerialize["registryPath"] = o.RegistryPath
	if !IsNil(o.Size) {
		toSerialize["size"] = o.Size
	}
	return toSerialize, nil
}

func (o *ArtifactVersionMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"registryIdentifier",
		"registryPath",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varArtifactVersionMetadata := _ArtifactVersionMetadata{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varArtifactVersionMetadata)

	if err != nil {
		return err
	}

	*o = ArtifactVersionMetadata(varArtifactVersionMetadata)

	return err
}

type NullableArtifactVersionMetadata struct {
	value *ArtifactVersionMetadata
	isSet bool
}

func (v NullableArtifactVersionMetadata) Get() *ArtifactVersionMetadata {
	return v.value
}

func (v *NullableArtifactVersionMetadata) Set(val *ArtifactVersionMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableArtifactVersionMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableArtifactVersionMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableArtifactVersionMetadata(val *ArtifactVersionMetadata) *NullableArtifactVersionMetadata {
	return &NullableArtifactVersionMetadata{value: val, isSet: true}
}

func (v NullableArtifactVersionMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableArtifactVersionMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


