/*
Harness Artifact Registry API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package har

import (
	"encoding/json"
)

// checks if the ClientSetupStepConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientSetupStepConfig{}

// ClientSetupStepConfig Client Setup Step
type ClientSetupStepConfig struct {
	Steps []ClientSetupStep `json:"steps,omitempty"`
}

// NewClientSetupStepConfig instantiates a new ClientSetupStepConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientSetupStepConfig() *ClientSetupStepConfig {
	this := ClientSetupStepConfig{}
	return &this
}

// NewClientSetupStepConfigWithDefaults instantiates a new ClientSetupStepConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientSetupStepConfigWithDefaults() *ClientSetupStepConfig {
	this := ClientSetupStepConfig{}
	return &this
}

// GetSteps returns the Steps field value if set, zero value otherwise.
func (o *ClientSetupStepConfig) GetSteps() []ClientSetupStep {
	if o == nil || IsNil(o.Steps) {
		var ret []ClientSetupStep
		return ret
	}
	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientSetupStepConfig) GetStepsOk() ([]ClientSetupStep, bool) {
	if o == nil || IsNil(o.Steps) {
		return nil, false
	}
	return o.Steps, true
}

// HasSteps returns a boolean if a field has been set.
func (o *ClientSetupStepConfig) HasSteps() bool {
	if o != nil && !IsNil(o.Steps) {
		return true
	}

	return false
}

// SetSteps gets a reference to the given []ClientSetupStep and assigns it to the Steps field.
func (o *ClientSetupStepConfig) SetSteps(v []ClientSetupStep) {
	o.Steps = v
}

func (o ClientSetupStepConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientSetupStepConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Steps) {
		toSerialize["steps"] = o.Steps
	}
	return toSerialize, nil
}

type NullableClientSetupStepConfig struct {
	value *ClientSetupStepConfig
	isSet bool
}

func (v NullableClientSetupStepConfig) Get() *ClientSetupStepConfig {
	return v.value
}

func (v *NullableClientSetupStepConfig) Set(val *ClientSetupStepConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableClientSetupStepConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableClientSetupStepConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientSetupStepConfig(val *ClientSetupStepConfig) *NullableClientSetupStepConfig {
	return &NullableClientSetupStepConfig{value: val, isSet: true}
}

func (v NullableClientSetupStepConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientSetupStepConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


