/*
Harness Artifact Registry API

Testing SpacesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package har

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_har_SpacesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SpacesAPIService GetAllHarnessArtifacts", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var spaceRef string

		resp, httpRes, err := apiClient.SpacesAPI.GetAllHarnessArtifacts(context.Background(), spaceRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SpacesAPIService GetAllRegistries", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var spaceRef string

		resp, httpRes, err := apiClient.SpacesAPI.GetAllRegistries(context.Background(), spaceRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SpacesAPIService GetArtifactStatsForSpace", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var spaceRef string

		resp, httpRes, err := apiClient.SpacesAPI.GetArtifactStatsForSpace(context.Background(), spaceRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SpacesAPIService GetStorageDetails", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var spaceRef string

		resp, httpRes, err := apiClient.SpacesAPI.GetStorageDetails(context.Background(), spaceRef).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
