// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// APIRestError api rest error
//
// swagger:model api.RestError
type APIRestError struct {

	// description
	Description string `json:"description,omitempty"`

	// message
	Message string `json:"message,omitempty"`
}

// Validate validates this api rest error
func (m *APIRestError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this api rest error based on context it is used
func (m *APIRestError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIRestError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIRestError) UnmarshalBinary(b []byte) error {
	var res APIRestError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
