// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComHarnessHceSaasGraphqlServerGraphModelIdentifiers github com harness hce saas graphql server graph model identifiers
//
// swagger:model github_com_harness_hce-saas_graphql_server_graph_model.Identifiers
type GithubComHarnessHceSaasGraphqlServerGraphModelIdentifiers struct {

	// Harness AccountID
	AccountIdentifier string `json:"accountIdentifier,omitempty"`

	// Harness OrgID
	OrgIdentifier string `json:"orgIdentifier,omitempty"`

	// Harness projectID
	ProjectIdentifier string `json:"projectIdentifier,omitempty"`
}

// Validate validates this github com harness hce saas graphql server graph model identifiers
func (m *GithubComHarnessHceSaasGraphqlServerGraphModelIdentifiers) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com harness hce saas graphql server graph model identifiers based on context it is used
func (m *GithubComHarnessHceSaasGraphqlServerGraphModelIdentifiers) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComHarnessHceSaasGraphqlServerGraphModelIdentifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComHarnessHceSaasGraphqlServerGraphModelIdentifiers) UnmarshalBinary(b []byte) error {
	var res GithubComHarnessHceSaasGraphqlServerGraphModelIdentifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
