// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GithubComHarnessHceSaasGraphqlServerGraphModelUserDetails github com harness hce saas graphql server graph model user details
//
// swagger:model github_com_harness_hce-saas_graphql_server_graph_model.UserDetails
type GithubComHarnessHceSaasGraphqlServerGraphModelUserDetails struct {

	// email
	Email string `json:"email,omitempty"`

	// user ID
	UserID string `json:"userID,omitempty"`

	// username
	Username string `json:"username,omitempty"`
}

// Validate validates this github com harness hce saas graphql server graph model user details
func (m *GithubComHarnessHceSaasGraphqlServerGraphModelUserDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this github com harness hce saas graphql server graph model user details based on context it is used
func (m *GithubComHarnessHceSaasGraphqlServerGraphModelUserDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GithubComHarnessHceSaasGraphqlServerGraphModelUserDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GithubComHarnessHceSaasGraphqlServerGraphModelUserDetails) UnmarshalBinary(b []byte) error {
	var res GithubComHarnessHceSaasGraphqlServerGraphModelUserDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
