// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// InfraV2Identifiers infra v2 identifiers
//
// swagger:model infra_v2.Identifiers
type InfraV2Identifiers struct {

	// account identifier
	AccountIdentifier string `json:"accountIdentifier,omitempty"`

	// org identifier
	OrgIdentifier string `json:"orgIdentifier,omitempty"`

	// project identifier
	ProjectIdentifier string `json:"projectIdentifier,omitempty"`
}

// Validate validates this infra v2 identifiers
func (m *InfraV2Identifiers) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this infra v2 identifiers based on context it is used
func (m *InfraV2Identifiers) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *InfraV2Identifiers) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InfraV2Identifiers) UnmarshalBinary(b []byte) error {
	var res InfraV2Identifiers
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
