// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ModelRecentWorkflowRun model recent workflow run
//
// swagger:model model.RecentWorkflowRun
type ModelRecentWorkflowRun struct {

	// Timestamp when the workflow was created
	CreatedAt string `json:"createdAt,omitempty"`

	// User who created the workflow run
	CreatedBy struct {
		GithubComHarnessHceSaasGraphqlServerGraphModelUserDetails
	} `json:"createdBy,omitempty"`

	// Notify ID for workflow run
	NotifyID string `json:"notifyID,omitempty"`

	// Phase of the workflow run
	Phase string `json:"phase,omitempty"`

	// Resiliency score of the workflow
	ResiliencyScore float64 `json:"resiliencyScore,omitempty"`

	// runSequence is the sequence number of experiment run
	RunSequence int64 `json:"runSequence,omitempty"`

	// Timestamp when the workflow was last updated
	UpdatedAt string `json:"updatedAt,omitempty"`

	// User who updated the workflow run
	UpdatedBy struct {
		GithubComHarnessHceSaasGraphqlServerGraphModelUserDetails
	} `json:"updatedBy,omitempty"`

	// ID of the workflow run which is to be queried
	WorkflowRunID string `json:"workflowRunID,omitempty"`
}

// Validate validates this model recent workflow run
func (m *ModelRecentWorkflowRun) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreatedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedBy(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelRecentWorkflowRun) validateCreatedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.CreatedBy) { // not required
		return nil
	}

	return nil
}

func (m *ModelRecentWorkflowRun) validateUpdatedBy(formats strfmt.Registry) error {
	if swag.IsZero(m.UpdatedBy) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this model recent workflow run based on the context it is used
func (m *ModelRecentWorkflowRun) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreatedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdatedBy(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ModelRecentWorkflowRun) contextValidateCreatedBy(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

func (m *ModelRecentWorkflowRun) contextValidateUpdatedBy(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *ModelRecentWorkflowRun) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ModelRecentWorkflowRun) UnmarshalBinary(b []byte) error {
	var res ModelRecentWorkflowRun
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
