// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SecurityGovernanceWorkload security governance workload
//
// swagger:model security_governance.Workload
type SecurityGovernanceWorkload struct {

	// application map Id
	ApplicationMapID string `json:"applicationMapId,omitempty"`

	// kind
	Kind string `json:"kind,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// services
	Services []string `json:"services"`
}

// Validate validates this security governance workload
func (m *SecurityGovernanceWorkload) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this security governance workload based on context it is used
func (m *SecurityGovernanceWorkload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SecurityGovernanceWorkload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SecurityGovernanceWorkload) UnmarshalBinary(b []byte) error {
	var res SecurityGovernanceWorkload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
