// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// V1SessionAffinityConfig v1 session affinity config
//
// swagger:model v1.SessionAffinityConfig
type V1SessionAffinityConfig struct {

	// clientIP contains the configurations of Client IP based session affinity.
	// +optional
	ClientIP struct {
		V1ClientIPConfig
	} `json:"clientIP,omitempty"`
}

// Validate validates this v1 session affinity config
func (m *V1SessionAffinityConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateClientIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SessionAffinityConfig) validateClientIP(formats strfmt.Registry) error {
	if swag.IsZero(m.ClientIP) { // not required
		return nil
	}

	return nil
}

// ContextValidate validate this v1 session affinity config based on the context it is used
func (m *V1SessionAffinityConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateClientIP(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1SessionAffinityConfig) contextValidateClientIP(ctx context.Context, formats strfmt.Registry) error {

	return nil
}

// MarshalBinary interface implementation
func (m *V1SessionAffinityConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SessionAffinityConfig) UnmarshalBinary(b []byte) error {
	var res V1SessionAffinityConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
