/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package idp

// Entity Version Create Request Body
type EntityVersionCreateRequest struct {
	// Entity YAML (to be passed as a String).
	Yaml string `json:"yaml"`
	// Version of the Entity.
	Version string `json:"version"`
	// Description of the EntityVersion. Will inherit the description from the Entity if not provided.
	Description string `json:"description,omitempty"`
	// Is the EntityVersion deprecated.
	Deprecated bool `json:"deprecated,omitempty"`
	// Is the EntityVersion stable. Only one EntityVersion can be stable at a time.
	Stable bool `json:"stable,omitempty"`
}
