/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type InfraV2UpgradeStatus string

// List of infra_v2.UpgradeStatus
const (
	UPGRADING_INFRA_InfraV2UpgradeStatus InfraV2UpgradeStatus = "UPGRADING_INFRA"
	UPGRADE_SKIPPED_InfraV2UpgradeStatus InfraV2UpgradeStatus = "UPGRADE_SKIPPED"
	UPGRADE_SUCCESSFUL_InfraV2UpgradeStatus InfraV2UpgradeStatus = "UPGRADE_SUCCESSFUL"
	UPGRADE_FAILED_InfraV2UpgradeStatus InfraV2UpgradeStatus = "UPGRADE_FAILED"
	DETECTING_UPGRADER_InfraV2UpgradeStatus InfraV2UpgradeStatus = "DETECTING_UPGRADER"
	UPGRADER_DISABLED_InfraV2UpgradeStatus InfraV2UpgradeStatus = "UPGRADER_DISABLED"
)
