/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type GithubComHarnessHceSaasGraphqlServerApiPagination struct {
	Index int32 `json:"index,omitempty"`
	Limit int32 `json:"limit,omitempty"`
	TotalItems int32 `json:"totalItems,omitempty"`
	TotalPages int32 `json:"totalPages,omitempty"`
}
