/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type TypesProbeType string

// List of types.ProbeType
const (
	HTTP_PROBE_TypesProbeType TypesProbeType = "httpProbe"
	CMD_PROBE_TypesProbeType TypesProbeType = "cmdProbe"
	PROM_PROBE_TypesProbeType TypesProbeType = "promProbe"
	K8S_PROBE_TypesProbeType TypesProbeType = "k8sProbe"
	SLO_PROBE_TypesProbeType TypesProbeType = "sloProbe"
	DATADOG_PROBE_TypesProbeType TypesProbeType = "datadogProbe"
	DYNATRACE_PROBE_TypesProbeType TypesProbeType = "dynatraceProbe"
	APM_PROBE_TypesProbeType TypesProbeType = "apmProbe"
	CONTAINER_PROBE_TypesProbeType TypesProbeType = "containerProbe"
)
