/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type RecommendationRecommendationSource string

// List of recommendation.RecommendationSource
const (
	CONFIG_SCANNER_RecommendationRecommendationSource RecommendationRecommendationSource = "ConfigScanner"
	K8S_WATCHER_RecommendationRecommendationSource RecommendationRecommendationSource = "K8sWatcher"
	INTERNAL_WATCHER_RecommendationRecommendationSource RecommendationRecommendationSource = "InternalWatcher"
)
