/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// inputs needed for the prometheus probe
type AllOfgithubComHarnessHceSaasHceSdkCommonProbeV1ProbePromProbeinputs struct {
	// Auth contains the authentication details for the prometheus probe
	Auth *interface{} `json:"auth,omitempty"`
	// Comparator check for the correctness of the probe output
	Comparator *interface{} `json:"comparator,omitempty"`
	// Endpoint for the prometheus probe
	Endpoint string `json:"endpoint,omitempty"`
	// Query to get prometheus metrics
	Query string `json:"query,omitempty"`
	// QueryPath contains filePath, which contains prometheus query
	QueryPath string `json:"queryPath,omitempty"`
	// TLSConfig contains the tls configuration for the prometheus probe
	TlsConfig *interface{} `json:"tlsConfig,omitempty"`
}
