/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.
type AllOfv1LabelSelectorRequirementOperator struct {
}
