/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type V1FlockerVolumeSource struct {
	// Name of the dataset stored as metadata -> name on the dataset for Flocker should be considered as deprecated +optional
	DatasetName string `json:"datasetName,omitempty"`
	// UUID of the dataset. This is unique identifier of a Flocker dataset +optional
	DatasetUUID string `json:"datasetUUID,omitempty"`
}
