/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type DatabaseDataCollectionConfiguration struct {
	BlacklistedNamespaces []string `json:"blacklistedNamespaces,omitempty"`
	CollectionWindowInMin int32 `json:"collectionWindowInMin,omitempty"`
	Cron *DatabaseCronConfig `json:"cron,omitempty"`
	EnableBatchResources bool `json:"enableBatchResources,omitempty"`
	EnableNodeAgent bool `json:"enableNodeAgent,omitempty"`
	EnableOrphanedPod bool `json:"enableOrphanedPod,omitempty"`
	NamespaceSelector string `json:"namespaceSelector,omitempty"`
	NodeAgentSelector string `json:"nodeAgentSelector,omitempty"`
	ObservedNamespaces []string `json:"observedNamespaces,omitempty"`
}
