/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ProbeInfrastructureType string

// List of probe.InfrastructureType
const (
	KUBERNETES_ProbeInfrastructureType ProbeInfrastructureType = "Kubernetes"
	KUBERNETES_V2_ProbeInfrastructureType ProbeInfrastructureType = "KubernetesV2"
	WINDOWS_ProbeInfrastructureType ProbeInfrastructureType = "Windows"
	LINUX_ProbeInfrastructureType ProbeInfrastructureType = "Linux"
	CLOUD_FOUNDRY_ProbeInfrastructureType ProbeInfrastructureType = "CloudFoundry"
	CONTAINER_ProbeInfrastructureType ProbeInfrastructureType = "Container"
)
