/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type TargetnetworkmapStatus string

// List of targetnetworkmap.Status
const (
	COMPLETED_TargetnetworkmapStatus TargetnetworkmapStatus = "COMPLETED"
	RUNNING_TargetnetworkmapStatus TargetnetworkmapStatus = "RUNNING"
	PENDING_TargetnetworkmapStatus TargetnetworkmapStatus = "PENDING"
	ERRORED_TargetnetworkmapStatus TargetnetworkmapStatus = "ERRORED"
)
