/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// PrometheusInputs contains the inputs required for prometheus probe
type AllOfv1ApmProbeInputsPrometheusInputs struct {
	// Endpoint for the prometheus probe
	Endpoint string `json:"endpoint,omitempty"`
	// Query to get prometheus metrics
	Query string `json:"query,omitempty"`
	// TLSConfig contains the tls configuration for the prometheus probe
	TlsConfig *interface{} `json:"tlsConfig,omitempty"`
}
