/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.67.16
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type InfraDeleteInfraRequest struct {
	CorrelationId string            `json:"correlationId,omitempty"`
	ForceDelete   bool              `json:"forceDelete,omitempty"`
	Identifier    *InfraIdentifiers `json:"identifier,omitempty"`
	InfraIDs      []string          `json:"infraIDs,omitempty"`
	InfraType     *InfraInfraType   `json:"infraType,omitempty"`
}
