/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ModelUpdateStatus string

// List of model.UpdateStatus
const (
	AVAILABLE_ModelUpdateStatus ModelUpdateStatus = "AVAILABLE"
	MANDATORY_ModelUpdateStatus ModelUpdateStatus = "MANDATORY"
	NOT_REQUIRED_ModelUpdateStatus ModelUpdateStatus = "NOT_REQUIRED"
)
