/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type V1ServiceAffinity string

// List of v1.ServiceAffinity
const (
	CLIENT_IP_V1ServiceAffinity V1ServiceAffinity = "ClientIP"
	NONE_V1ServiceAffinity V1ServiceAffinity = "None"
)
