/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type InfraV2InstallationType string

// List of infra_v2.InstallationType
const (
	CONNECTOR_InfraV2InstallationType InfraV2InstallationType = "CONNECTOR"
	MANIFEST_InfraV2InstallationType InfraV2InstallationType = "MANIFEST"
	CONNECTOR_V2_InfraV2InstallationType InfraV2InstallationType = "CONNECTOR_V2"
)
