/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ProbeSloProbeTemplate struct {
	Comparator *ProbeComparatorTemplate `json:"comparator,omitempty"`
	EvaluationTimeout string `json:"evaluationTimeout,omitempty"`
	EvaluationWindow *ProbeEvaluationWindowTemplate `json:"evaluationWindow,omitempty"`
	InsecureSkipVerify bool `json:"insecureSkipVerify,omitempty"`
	PlatformEndpoint string `json:"platformEndpoint,omitempty"`
	SloIdentifier string `json:"sloIdentifier,omitempty"`
	SloSourceMetadata *ProbeSloSourceMetadataTemplate `json:"sloSourceMetadata,omitempty"`
}
