/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// Details for fetching paginated data
type AllOfmodelListWorkflowRequestPagination struct {
	// Number of data to be fetched
	Limit int32 `json:"limit,omitempty"`
	// Page number for which data will be fetched
	Page int32 `json:"page,omitempty"`
}
