/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type DatabaseNetworkMapResourceKind string

// List of database.NetworkMapResourceKind
const (
	K8_S_CUSTOM_SERVICE_DatabaseNetworkMapResourceKind DatabaseNetworkMapResourceKind = "K8SCustomService"
	DISCOVEREDSERVICE_DatabaseNetworkMapResourceKind DatabaseNetworkMapResourceKind = "discoveredservice"
)
