/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type DatabaseDiscoveredServiceSpec struct {
	Fqdn []string `json:"fqdn,omitempty"`
	HarnessEnvironmentIdentity *DatabaseEnvironmentIdentity `json:"harnessEnvironmentIdentity,omitempty"`
	HarnessServiceIdentity *DatabaseServiceIdentity `json:"harnessServiceIdentity,omitempty"`
	Ip []string `json:"ip,omitempty"`
	Kubernetes *DatabaseDiscoveredServiceKubernetesSpec `json:"kubernetes,omitempty"`
	Port []string `json:"port,omitempty"`
}
