/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type CommonVolumeType string

// List of common.VolumeType
const (
	HOST_PATH_CommonVolumeType CommonVolumeType = "HostPath"
	EMPTY_DIR_CommonVolumeType CommonVolumeType = "EmptyDir"
	SECRET_CommonVolumeType CommonVolumeType = "Secret"
	PERSISTENT_VOLUME_CLAIM_CommonVolumeType CommonVolumeType = "PersistentVolumeClaim"
	CONFIG_MAP_CommonVolumeType CommonVolumeType = "ConfigMap"
)
