/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type CommonResourceRequirements struct {
	Limits map[string]string `json:"limits,omitempty"`
	Requests map[string]string `json:"requests,omitempty"`
}
