/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type DatabaseDiscoveredKubernetesWorkload struct {
	Annotations map[string]string `json:"annotations,omitempty"`
	Identity *V1ObjectReference `json:"identity,omitempty"`
	Labels map[string]string `json:"labels,omitempty"`
	PodAnnotations map[string]string `json:"podAnnotations,omitempty"`
	PodLabels map[string]string `json:"podLabels,omitempty"`
	Replicas []DatabaseDiscoveredPod `json:"replicas,omitempty"`
}
