/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type TypesCreateGamedayRequest struct {
	Experiments []TypesExperimentRequest `json:"experiments,omitempty"`
	GameDayID string `json:"gameDayID,omitempty"`
	GamedayDescription string `json:"gamedayDescription,omitempty"`
	GamedayName string `json:"gamedayName,omitempty"`
	Objective string `json:"objective,omitempty"`
	Prerequisites []TypesPrerequisite `json:"prerequisites,omitempty"`
	Stakeholders []TypesStakeHolderInput `json:"stakeholders,omitempty"`
}
