/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// AppdMetrics contains the appd metrics
type AllOfv1AppDynamicsInputsAppdMetrics struct {
	// ApplicationName contains the application name
	ApplicationName string `json:"applicationName,omitempty"`
	// DurationInMin contains the duration in minutes
	DurationInMin int32 `json:"durationInMin,omitempty"`
	// MetricsFullPath contains the full path of the metrics
	MetricsFullPath string `json:"metricsFullPath,omitempty"`
}
