/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ModelGetInfraStatsResponse struct {
	// Total number of active infrastructures
	TotalActiveInfrastructure int32 `json:"totalActiveInfrastructure,omitempty"`
	// Total number of confirmed infrastructures
	TotalConfirmedInfrastructure int32 `json:"totalConfirmedInfrastructure,omitempty"`
	// Total number of inactive infrastructures
	TotalInactiveInfrastructures int32 `json:"totalInactiveInfrastructures,omitempty"`
	// Total number of infrastructures
	TotalInfrastructures int32 `json:"totalInfrastructures,omitempty"`
	// Total number of non confirmed infrastructures
	TotalNonConfirmedInfrastructures int32 `json:"totalNonConfirmedInfrastructures,omitempty"`
}
