/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.67.16
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// type of the test; supports 'api' and 'browser' only
type AllOfv1SyntheticsTestTestType string

const (
	TestTypeApi     AllOfv1SyntheticsTestTestType = "api"
	TestTypeBrowser AllOfv1SyntheticsTestTestType = "browser"
)

func (v AllOfv1SyntheticsTestTestType) String() string {
	return string(v)
}
