/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// LoadBalancer contains the current status of the load-balancer, if one is present. +optional
type AllOfv1ServiceStatusLoadBalancer struct {
	// Ingress is a list containing ingress points for the load-balancer. Traffic intended for the service should be sent to these ingress points. +optional
	Ingress []V1LoadBalancerIngress `json:"ingress,omitempty"`
}
