/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// Method define the http method, it can be get or post
type AllOfgithubComHarnessHceSaasHceSdkCommonProbeV1HttpProbeInputsMethod struct {
	Get *GithubComHarnessHceSaasHceSdkCommonProbeV1GetMethod `json:"get,omitempty"`
	Post *GithubComHarnessHceSaasHceSdkCommonProbeV1PostMethod `json:"post,omitempty"`
}
