/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type V1SloSourceMetadata struct {
	// APITokenSecret for authenticating with the platform service
	ApiTokenSecret string `json:"apiTokenSecret,omitempty"`
	// Scope required for fetching details
	Scope *AllOfv1SloSourceMetadataScope `json:"scope,omitempty"`
}
