/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

// TBD use ConnectorRef and deprecate it
type AllOfchaoshubv2GetHubResponseConnectorScope string

const (
	AllOfchaoshubv2GetHubResponseConnectorScopeAccount      AllOfchaoshubv2GetHubResponseConnectorScope = "ACCOUNT"
	AllOfchaoshubv2GetHubResponseConnectorScopeProject      AllOfchaoshubv2GetHubResponseConnectorScope = "PROJECT"
	AllOfchaoshubv2GetHubResponseConnectorScopeOrganisation AllOfchaoshubv2GetHubResponseConnectorScope = "ORGANISATION"
)
