/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type TypesCreateGamedayRunResponse struct {
	Data *TypesRun `json:"data,omitempty"`
	ExperimentError []TypesExperimentCreationError `json:"experimentError,omitempty"`
}
