/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type HandlersDashboard struct {
	Description string `json:"description,omitempty"`
	Id int32 `json:"id,omitempty"`
	Title string `json:"title,omitempty"`
}
