/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type TypesCreateNoteRequest struct {
	Comment string `json:"comment,omitempty"`
	ExperimentID string `json:"experimentID,omitempty"`
	ExperimentRunID string `json:"experimentRunID,omitempty"`
	GamedayRunID string `json:"gamedayRunID,omitempty"`
	Type_ *ChaosresourcenotesNoteType `json:"type,omitempty"`
}
