/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type InfraV2ListKubernetesInfraV2Request struct {
	Filter *InfraV2KubernetesInfraV2FilterInput `json:"filter,omitempty"`
	Identifier *InfraV2Identifiers `json:"identifier,omitempty"`
	Sort *InfraV2SortInput `json:"sort,omitempty"`
}
