/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ProbeTlsConfigTemplate struct {
	CaFile string `json:"caFile,omitempty"`
	CertFile string `json:"certFile,omitempty"`
	InsecureSkipVerify bool `json:"insecureSkipVerify,omitempty"`
	KeyFile string `json:"keyFile,omitempty"`
}
