/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type TypesCreateProbeResponse struct {
	ApmProperties *ProbeApmProbe `json:"apmProperties,omitempty"`
	ContainerHttpProperties *ProbeHttpProbe `json:"containerHttpProperties,omitempty"`
	ContainerProbeProperties *ProbeContainerProbe `json:"containerProbeProperties,omitempty"`
	Description string `json:"description,omitempty"`
	K8sProperties *ProbeK8SProbe `json:"k8sProperties,omitempty"`
	KubernetesCmdProperties *ProbeKubernetesCmdProbe `json:"kubernetesCmdProperties,omitempty"`
	KubernetesDatadogProperties *ProbeDatadogProbe `json:"kubernetesDatadogProperties,omitempty"`
	KubernetesDynatraceProperties *ProbeDynatraceProbe `json:"kubernetesDynatraceProperties,omitempty"`
	KubernetesHttpProperties *ProbeHttpProbe `json:"kubernetesHttpProperties,omitempty"`
	LinuxCmdProperties *ProbeLinuxCmdProbe `json:"linuxCmdProperties,omitempty"`
	LinuxDatadogProperties *ProbeDatadogProbe `json:"linuxDatadogProperties,omitempty"`
	LinuxDynatraceProperties *ProbeDynatraceProbe `json:"linuxDynatraceProperties,omitempty"`
	LinuxHttpProperties *ProbeHttpProbe `json:"linuxHttpProperties,omitempty"`
	Name string `json:"name,omitempty"`
	ProbeId string `json:"probeId,omitempty"`
	PromProperties *ProbePromProbe `json:"promProperties,omitempty"`
	RevisionId string `json:"revisionId,omitempty"`
	SloProperties *ProbeSloProbe `json:"sloProperties,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Variables []TemplateVariable `json:"variables,omitempty"`
	WindowsCmdProperties *ProbeWindowsCmdProbe `json:"windowsCmdProperties,omitempty"`
	WindowsHttpProperties *ProbeHttpProbe `json:"windowsHttpProperties,omitempty"`
}
