/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.67.16
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type ProbeSyntheticsTest struct {
	PublicId string                                                                                `json:"publicId,omitempty"`
	TestType *GithubComHarnessHceSaasGraphqlServerPkgDatabaseMongodbProbeDatadogSyntheticsTestType `json:"testType,omitempty"`
}
