/*
 * Chaos Manager
 *
 * ChaosManager serves as the primary API server for the chaos module, responsible for transferring and handling requests to their respective operations
 *
 * API version: 1.72.9
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package chaos

type V2OnboardingConfirmDiscoveryResponse struct {
	AgentCreated bool `json:"agentCreated,omitempty"`
	AgentLinked bool `json:"agentLinked,omitempty"`
	DiscoveryCompleted bool `json:"discoveryCompleted,omitempty"`
}
