/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TypesTemplate struct {
	Created int32 `json:"created,omitempty"`
	Data string `json:"data,omitempty"`
	Description string `json:"description,omitempty"`
	Id int32 `json:"id,omitempty"`
	SpaceId int32 `json:"space_id,omitempty"`
	Uid string `json:"uid,omitempty"`
	Updated int32 `json:"updated,omitempty"`
}
