/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TypesUser struct {
	Admin bool `json:"admin,omitempty"`
	Blocked bool `json:"blocked,omitempty"`
	Created int32 `json:"created,omitempty"`
	DisplayName string `json:"display_name,omitempty"`
	Email string `json:"email,omitempty"`
	Uid string `json:"uid,omitempty"`
	Updated int32 `json:"updated,omitempty"`
}
