/*
 * API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type EnumParentResourceType string

// List of EnumParentResourceType
const (
	SPACE_EnumParentResourceType EnumParentResourceType = "space"
	REPO_EnumParentResourceType EnumParentResourceType = "repo"
)
